language: objective-c
osx_image: xcode8.3

env:
  global:
    - DESTINATION="platform=iOS Simulator,name=iPhone 7"


before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  
script:
  - set -o pipefail
  - cd ios/AMPKitDemo
  - pod install --repo-update
  - xcodebuild test -workspace AMPKitDemo.xcworkspace/ -scheme AMPKitDemoTests -sdk iphonesimulator -destination $DESTINATION
